export const DEMOTIVATIONAL_QUOTES: readonly string[] = [
  "Don't worry about the world coming to an end today. It's already tomorrow in Australia.",
  "You're not lazy, you're just on energy-saving mode.",
  'Why do it today when you can put it off till tomorrow?',
  'Life is short. Smile while you still have teeth.',
  'Age is just a number, and so is your bank balance.',
  "Some people are like clouds. When they disappear, it's a beautiful day.",
  "I'm great at multitasking. I can waste time, be unproductive, and procrastinate all at once.",
  "Opportunity does knock once, but by the time you stop looking through the peephole, it's gone.",
  'A clear conscience is usually the sign of a bad memory.',
  'Laugh and the world laughs with you. Snore and you sleep alone.',
  "You can't have everything. Where would you put it?",
  'The problem with troubleshooting is that sometimes trouble shoots back.',
  'Remember, it’s only a game, unless you’re losing.',
  'If you’re not part of the solution, there’s good money to be made in prolonging the problem.',
  'The best thing about hitting rock bottom is the discovery that rock bottom has a basement.',
  'An expert is someone who knows more and more about less and less, until eventually, they know everything about nothing.',
  'Money can’t buy happiness, but it sure makes misery easier to live with.',
  "If at first you don't succeed, look in the trash for the instructions.",
  'To steal ideas from one person is plagiarism; to steal from many is research.',
  'Remember, when you’re going through hell, keep going. You might get out before the devil even knows you’re there.',
  'Achieving success is like finding a needle in a haystack, except the needle is also made of hay.',
  'Dreams are like rainbows. Only idiots chase them.',
  "It's always too early to quit, but never too late to give up.",
  'The road to success is dotted with many tempting parking spaces.',
  'Hard work never killed anyone, but why take the chance?',
  "Remember, Rome wasn't built in a day. But it burned in one.",
  'The light at the end of the tunnel has been turned off due to budget cuts.',
  "If at first you don't succeed, failure may be your style.",
  'Teamwork is important; it helps to put the blame on someone else.',
  'If you try to fail, and succeed, which have you done?',
  'Experience is a wonderful thing. It enables you to recognize a mistake when you make it again.',
  "If you can't learn to do it well, learn to enjoy doing it badly.",
  'Don’t follow your dreams, they’re probably unreachable.',
  "Be the kind of person that when your feet hit the floor each morning, the devil says, 'Oh crap, they're up.'",
  'Life is full of disappointments, and I just added you to the list.',
  'If you think nobody cares if you’re alive, try missing a couple of payments.',
  "A diamond is merely a lump of coal that did well under pressure. So, you're probably not a diamond.",
  'Motivation is what gets you started. Habit is why you keep making the same mistakes.',
  'Someday we’ll look back on all this and plow into a parked car.',
  'There are no stupid questions, but there are a LOT of inquisitive idiots.',
  'If the grass is greener on the other side, maybe that’s because you’re not there.',
  'I am not a pessimist. I am an optimist who has experienced the realities of life.',
  'Remember, you are unique, just like everyone else.',
  'Not all who wander are lost, but you probably are.',
  'I don’t believe in astrology; I’m a Sagittarius and we’re skeptical.',
  'Always borrow money from a pessimist. They won’t expect it back.',
  'Hard work pays off in the future. Laziness pays off now.',
  "If at first you don't succeed, then skydiving definitely isn't for you.",
  'If you think education is expensive, try ignorance.',
  'The early bird might get the worm, but the second mouse gets the cheese.',
  'I didn’t say it was your fault, I said I was blaming you.',
  'Life is like a sewer… what you get out of it depends on what you put into it.',
  'You’re never too old to learn something stupid.',
  'To err is human, to blame it on someone else shows management potential.',
  "If two wrongs don't make a right, try three.",
  'The journey of a thousand miles begins with a single step. So does walking into a wall.',
  'Believe in yourself. Someone has to.',
  "You miss 100% of the naps you don't take.",
  'Every day is a new opportunity to lower your expectations until they match reality.',
  "Aim for the stars. That way you'll miss everything at a safe distance.",
  'You are capable of amazing things. Statistically unlikely, but capable.',
  'Every accomplishment starts with the decision to try, and ends shortly after.',
  'Your comfort zone called. It misses you. Go home.',
  'Genius is 1% inspiration and 99% checking your phone.',
  'Nothing is impossible. Which is a shame — you were counting on that excuse.',
  'The secret of getting ahead is getting started. Staying behind requires no secret at all.',
  "It's not procrastination — you're just waiting for a version of you that never shows up.",
  "Shoot for the moon. Even if you miss, you'll drift uselessly through the void, which sounds familiar.",
  "Don't put off till tomorrow what you can put off till next week.",
  'Hard days build character. Easy days build nothing, which is also fine.',
];
